# Use the official Flink image as a base
FROM flink:latest

# Install Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Optional: Install any required Python packages
RUN pip3 install pyflink

# Set the working directory
WORKDIR /app

# Copy your Python scripts into the container
COPY app/flink_processor.py /app/

# Default command to run Flink
CMD ["jobmanager"]
